export enum Categorias {
  ALIMENTACAO = 'ALIMENTACAO',
  ESTUDOS = 'ESTUDOS',
  MORADIA = 'MORADIA',
  TRANSPORTE = 'TRANSPORTE',
  SAUDE = 'SAUDE',
  LAZER = 'LAZER',
  INVESTIMENTOS = 'INVESTIMENTOS',
  IFOOD = 'IFOOD',
  OUTROS = 'OUTROS',
}
